name: The Coaching Store
favicon: null
layout_spectrum: 0.20114930113777518
typography_spectrum: 0.4979560347273946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fd5e0c'
    - '#607078'
    - '#131517'
    - '#a2adb1'
  brandStrength: 0.19368661986663938
  lightness: 0.2500002272427082
  saturation: 0.30401329789310694
  rhythmicContrast: 0.07732978696003556
purpose: []
